# Generated by Django 5.0.6 on 2024-11-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_rename_participant_1_studentdetail_participant_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='task',
        ),
    ]
